# Generated by Django 4.0.3 on 2022-04-22 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WatermarkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.BigIntegerField(null=True)),
                ('height', models.BigIntegerField(null=True)),
                ('img', models.ImageField(blank=True, default='', upload_to='watermark/media/img/')),
                ('logo', models.ImageField(blank=True, default='', upload_to='watermark/media/logo/')),
            ],
        ),
    ]
